In [1]:
import numpy as np

In [2]:
arr=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(arr)

In [3]:
# np.shape
print(arr.shape)

(3, 3)


In [4]:
# .ndim-- no. of dimension
print(arr.ndim)

2


In [5]:
# .size--no. of elements
print(arr.size)

9


In [6]:
# =========INDEXING AND SLICING============

In [7]:
arr=np.array([1,23,4,5,6])


# 1d array list and slicing =list

In [9]:
print(arr[1])
print(arr[-3])

23
4


In [10]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# INDEXING--------

print(arr[1,2])
print(arr[2,-1])

6
9


In [25]:
# SLICING--------

# arr[rStart:rEnd;rStep , cStart:cEnd:cStep]
print(arr[0:2:1,0:2:1])
print(arr[1::1,1::1])
print(arr[1:,1:2])

[[1 2]
 [4 5]]
[[5 6]
 [8 9]]
[[5]
 [8]]


In [26]:
# BOoolean indexing

In [30]:
arr= np.array([1,2,3,4,5])
print(arr>=5)
print(arr[arr>2])

[False False False False  True]
[3 4 5]
