In [1]:
import numpy as np

In [2]:
l=[1020,30]

In [3]:
arr=np.array(l)
arr

array([1020,   30])

In [4]:
a=[[1,2,3],[4,5,6],[7,8,9]]

matrix= np.array(a)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr= np.zeros([5,6])
arr


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
arr=np.ones([6,6])
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
arr=np.arange(1,20,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
arr=np.linspace(0,10,3)
arr

array([ 0.,  5., 10.])

In [12]:
np.full(10,7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [13]:
np.full([4,4],11)

array([[11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11]])

In [14]:
np.eye(4)      # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(2,3)

array([[0.15358484, 0.0646488 , 0.65099107],
       [0.90972187, 0.23052421, 0.95153967]])

In [22]:
# np.random.randint(start,end,(rows,col))
np.random.randint(1,20,(2,3))  

array([[12,  6, 14],
       [10,  6, 11]], dtype=int32)